pipeline:
  name: Deploy Spark Operator - All Clusters
  identifier: Deploy_Spark_Operator_To_All
  projectIdentifier: Spark
  orgIdentifier: RelativityOne_Compute
  tags: {}
  stages:
    - stage:
        name: CTUS Stage
        identifier: CTUS_Stage
        description: ""
        type: Pipeline
        spec:
          org: RelativityOne_Compute
          pipeline: Deploy_Spark_Operator
          project: Spark
          inputs:
            identifier: Deploy_Spark_Operator
            stages:
              - stage:
                  identifier: Deploy_Relativity_Components
                  type: Deployment
                  spec:
                    environment:
                      environmentRef: prod
                      infrastructureDefinitions:
                        - identifier: stage
          outputs: []
    - stage:
        name: CTUS Sand
        identifier: CTUS_Sand
        description: ""
        type: Pipeline
        spec:
          org: RelativityOne_Compute
          pipeline: Deploy_Spark_Operator
          project: Spark
          inputs:
            identifier: Deploy_Spark_Operator
            stages:
              - stage:
                  identifier: Deploy_Relativity_Components
                  type: Deployment
                  spec:
                    environment:
                      environmentRef: prod
                      infrastructureDefinitions:
                        - identifier: ctusk8ssand1
          outputs: []
    - stage:
        name: AUEA
        identifier: AUEA
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Spark_Operator
          environment:
            environmentRef: prod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: aueak8sprod1b
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - parallel:
        - stage:
            name: UKSO
            identifier: UKSO
            description: ""
            type: Deployment
            spec:
              deploymentType: Kubernetes
              service:
                serviceRef: Spark_Operator
              environment:
                environmentRef: prod
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: uksok8sprod1a
              execution:
                steps:
                  - step:
                      name: Rollout Deployment
                      identifier: rolloutDeployment
                      type: K8sRollingDeploy
                      timeout: 10m
                      spec:
                        skipDryRun: false
                        pruningEnabled: false
                rollbackSteps:
                  - step:
                      name: Rollback Rollout Deployment
                      identifier: rollbackRolloutDeployment
                      type: K8sRollingRollback
                      timeout: 10m
                      spec:
                        pruningEnabled: false
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
        - stage:
            name: WSEU
            identifier: WSEU
            description: ""
            type: Deployment
            spec:
              deploymentType: Kubernetes
              service:
                serviceRef: Spark_Operator
              environment:
                environmentRef: prod
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: wseuk8sprod1b
              execution:
                steps:
                  - step:
                      name: Rollout Deployment
                      identifier: rolloutDeployment
                      type: K8sRollingDeploy
                      timeout: 10m
                      spec:
                        skipDryRun: false
                        pruningEnabled: false
                rollbackSteps:
                  - step:
                      name: Rollback Rollout Deployment
                      identifier: rollbackRolloutDeployment
                      type: K8sRollingRollback
                      timeout: 10m
                      spec:
                        pruningEnabled: false
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
        - stage:
            name: CHNO
            identifier: CHNO
            description: ""
            type: Deployment
            spec:
              deploymentType: Kubernetes
              service:
                serviceRef: Spark_Operator
              environment:
                environmentRef: prod
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: wseuk8sprod1b
              execution:
                steps:
                  - step:
                      name: Rollout Deployment
                      identifier: rolloutDeployment
                      type: K8sRollingDeploy
                      timeout: 10m
                      spec:
                        skipDryRun: false
                        pruningEnabled: false
                rollbackSteps:
                  - step:
                      name: Rollback Rollout Deployment
                      identifier: rollbackRolloutDeployment
                      type: K8sRollingRollback
                      timeout: 10m
                      spec:
                        pruningEnabled: false
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
        - stage:
            name: DECT
            identifier: DECT
            description: ""
            type: Deployment
            spec:
              deploymentType: Kubernetes
              service:
                serviceRef: Spark_Operator
              environment:
                environmentRef: prod
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: wseuk8sprod1b
              execution:
                steps:
                  - step:
                      name: Rollout Deployment
                      identifier: rolloutDeployment
                      type: K8sRollingDeploy
                      timeout: 10m
                      spec:
                        skipDryRun: false
                        pruningEnabled: false
                rollbackSteps:
                  - step:
                      name: Rollback Rollout Deployment
                      identifier: rollbackRolloutDeployment
                      type: K8sRollingRollback
                      timeout: 10m
                      spec:
                        pruningEnabled: false
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
        - stage:
            name: NOEU
            identifier: NOEU
            description: ""
            type: Deployment
            spec:
              deploymentType: Kubernetes
              service:
                serviceRef: Spark_Operator
              environment:
                environmentRef: prod
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: wseuk8sprod1b
              execution:
                steps:
                  - step:
                      name: Rollout Deployment
                      identifier: rolloutDeployment
                      type: K8sRollingDeploy
                      timeout: 10m
                      spec:
                        skipDryRun: false
                        pruningEnabled: false
                rollbackSteps:
                  - step:
                      name: Rollback Rollout Deployment
                      identifier: rollbackRolloutDeployment
                      type: K8sRollingRollback
                      timeout: 10m
                      spec:
                        pruningEnabled: false
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
        - stage:
            name: FRCT
            identifier: FRCT
            description: ""
            type: Deployment
            spec:
              deploymentType: Kubernetes
              service:
                serviceRef: Spark_Operator
              environment:
                environmentRef: prod
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: wseuk8sprod1b
              execution:
                steps:
                  - step:
                      name: Rollout Deployment
                      identifier: rolloutDeployment
                      type: K8sRollingDeploy
                      timeout: 10m
                      spec:
                        skipDryRun: false
                        pruningEnabled: false
                rollbackSteps:
                  - step:
                      name: Rollback Rollout Deployment
                      identifier: rollbackRolloutDeployment
                      type: K8sRollingRollback
                      timeout: 10m
                      spec:
                        pruningEnabled: false
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
        - stage:
            name: ZANO
            identifier: ZANO
            description: ""
            type: Deployment
            spec:
              deploymentType: Kubernetes
              service:
                serviceRef: Spark_Operator
              environment:
                environmentRef: prod
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: wseuk8sprod1b
              execution:
                steps:
                  - step:
                      name: Rollout Deployment
                      identifier: rolloutDeployment
                      type: K8sRollingDeploy
                      timeout: 10m
                      spec:
                        skipDryRun: false
                        pruningEnabled: false
                rollbackSteps:
                  - step:
                      name: Rollback Rollout Deployment
                      identifier: rollbackRolloutDeployment
                      type: K8sRollingRollback
                      timeout: 10m
                      spec:
                        pruningEnabled: false
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
