pipeline:
  name: Deploy Spark Operator
  identifier: Deploy_Spark_Operator
  projectIdentifier: Spark
  orgIdentifier: RelativityOne_Compute
  tags: {}
  stages:
    - stage:
        name: Create CR
        identifier: Create_CR
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: JiraCreate
                  name: Create CR
                  identifier: Create_CR
                  spec:
                    connectorRef: account.Jira_Connector
                    projectKey: SDSD
                    issueType: Change Request
                    fields:
                      - name: Backout Time
                        value: < 30 min
                      - name: Business Impact of Failure
                        value: Low
                      - name: Change Complexity
                        value: Easy
                      - name: Change Reason
                        value: CI/CD Deployment
                      - name: Change Type
                        value: Standard
                      - name: Changelog / Release Notes
                        value: https://github.com/relativityone/spark-operator/commits/main
                      - name: Deployment Method
                        value: Other
                      - name: Impact
                        value: Low
                      - name: Implementation Steps
                        value: Create CR, Deploy, Verify, Close CR
                      - name: Monitoring / Alerts
                        value: New Relic,Splunk
                      - name: Planned Duration
                        value: "5"
                      - name: Planned Start Date/Time
                        value: current()
                      - name: Requested Date/Time
                        value: current()
                      - name: Requires Downtime
                        value: "No"
                      - name: Security Impact Assessment
                        value: Not Required
                      - name: Testing Evidence
                        value: Previous rings were successful
                      - name: Testing Performed
                        value: Routine Operational Activity
                      - name: Uses Automation
                        value: "Yes"
                      - name: Verification Steps
                        value: Automatic within workflow
                      - name: Category
                        value: Cloud Infrastructure
                      - name: Customer Benefit
                        value: Improved customer experience with iterative, transparent changes.
                      - name: Subcategory
                        value: Install/Upgrade
                      - name: Summary
                        value: "Update K8s Applications: Spark Operator Components"
                  timeout: 10m
              - step:
                  type: JiraUpdate
                  name: CR Ready for Work
                  identifier: CR_Ready_for_Work
                  spec:
                    connectorRef: account.Jira_Connector
                    issueKey: <+pipeline.stages.Jira_Stage.spec.execution.steps.CreateCR.issue.key>
                    transitionTo:
                      status: Ready for Work
                    fields: []
                  timeout: 10m
              - step:
                  type: JiraUpdate
                  name: CR In Progress
                  identifier: CR_In_Progress
                  spec:
                    connectorRef: account.Jira_Connector
                    issueKey: <+pipeline.stages.Jira_Stage.spec.execution.steps.CreateCR.issue.key>
                    transitionTo:
                      status: In Progress
                    fields: []
                  timeout: 10m
        tags: {}
        when:
          pipelineStatus: Success
          condition: <+env.name> == "prod"
    - stage:
        name: Deploy Relativity Components
        identifier: Deploy_Relativity_Components
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Relativity_Components
          environment:
            environmentRef: <+input>
            deployToAll: false
            environmentInputs: <+input>
            serviceOverrideInputs: <+input>
            infrastructureDefinitions: <+input>
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: Deploy Spark Operator
        identifier: Deploy_Spark_Operator
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Spark_Operator
          environment:
            environmentRef: <+pipeline.stages.Deploy_Relativity_Components.spec.env.name>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: <+pipeline.stages.Deploy_Relativity_Components.spec.infrastructure>
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: Spark Pi Canary
        identifier: Spark_Pi_Canary
        description: ""
        type: Pipeline
        spec:
          org: RelativityOne_Compute
          pipeline: Spark_Pi_Smoke_Test
          project: Spark
          inputs:
            identifier: Spark_Pi_Smoke_Test
            stages:
              - stage:
                  identifier: Deploy
                  type: Deployment
                  spec:
                    environment:
                      environmentRef: <+pipeline.stages.Deploy_Relativity_Components.spec.env.environmentRef>
                      infrastructureDefinitions:
                        - identifier: <+pipeline.stages.Deploy_Relativity_Components.spec.infrastructure>
            variables:
              - name: branch
                type: String
                value: <+pipeline.variables.branch>
          outputs: []
    - stage:
        name: Close CR
        identifier: Close_CR
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: JiraUpdate
                  name: Close CR
                  identifier: Close_CR
                  spec:
                    connectorRef: account.Jira_Connector
                    issueKey: <+pipeline.stages.Jira_Stage.spec.execution.steps.CreateCR.issue.key>
                    fields: []
                  timeout: 10m
        tags: {}
  variables:
    - name: branch
      type: String
      description: ""
      required: true
      value: main
