pipeline:
  name: Deploy Spark Operator - All Clusters
  identifier: Deploy_Spark_Operator_To_All
  projectIdentifier: Spark
  orgIdentifier: RelativityOne_Compute
  tags: {}
  stages:
    - stage:
        name: CTUS Stage
        identifier: CTUS_Stage
        description: ""
        type: Pipeline
        spec:
          org: RelativityOne_Compute
          pipeline: Deploy_Spark_Operator
          project: Spark
          inputs:
            identifier: Deploy_Spark_Operator
            stages:
              - stage:
                  identifier: Deploy_Relativity_Components
                  type: Deployment
                  spec:
                    environment:
                      environmentRef: prod
                      infrastructureDefinitions:
                        - identifier: stage
          outputs: []
    - stage:
        name: CTUS Sand
        identifier: CTUS_Sand
        description: ""
        type: Pipeline
        spec:
          org: RelativityOne_Compute
          pipeline: Deploy_Spark_Operator
          project: Spark
          inputs:
            identifier: Deploy_Spark_Operator
            stages:
              - stage:
                  identifier: Deploy_Relativity_Components
                  type: Deployment
                  spec:
                    environment:
                      environmentRef: prod
                      infrastructureDefinitions:
                        - identifier: ctusk8ssand1
          outputs: []
    - stage:
        name: Ring 4 Approval
        identifier: Ring_4_Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Approval
                  identifier: Approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - _project_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: AUEA
        identifier: AUEA
        description: ""
        type: Pipeline
        spec:
          org: RelativityOne_Compute
          pipeline: Deploy_Spark_Operator
          project: Spark
          inputs:
            identifier: Deploy_Spark_Operator
            stages:
              - stage:
                  identifier: Deploy_Relativity_Components
                  type: Deployment
                  spec:
                    environment:
                      environmentRef: prod
                      infrastructureDefinitions:
                        - identifier: aueak8sprod1b
    - stage:
        name: Ring 5 Approval
        identifier: Ring_5_Approval
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Approval
                  identifier: Approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - _project_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - parallel:
        - stage:
            name: UKSO
            identifier: UKSO
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: uksok8sprod1a
        - stage:
            name: WSEU
            identifier: WSEU
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: wseuk8sprod1b
        - stage:
            name: CHNO
            identifier: CHNO
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: chnok8sprod1a
        - stage:
            name: DECT
            identifier: DECT
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: dectk8sprod1a
        - stage:
            name: NOEU
            identifier: NOEU
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: noeuk8sprod1b
        - stage:
            name: FRCT
            identifier: FRCT
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: frctk8sprod1a
        - stage:
            name: ZANO
            identifier: ZANO
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: zano01k8sprod
    - parallel:
        - stage:
            name: ESAS
            identifier: ESAS
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: esask8sprod1b
        - stage:
            name: KRCT
            identifier: KRCT
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: krctk8sprod1b
        - stage:
            name: SEAS
            identifier: SEAS
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: seask8sprod1b
        - stage:
            name: AENO
            identifier: AENO
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: aenok8sprod1b
        - stage:
            name: INCT
            identifier: INCT
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: inctk8sprod1b
        - stage:
            name: JPES
            identifier: JPES
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: jpesk8sprod1
    - parallel:
        - stage:
            name: BRSO
            identifier: BRSO
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: brsok8sprod1b
        - stage:
            name: CACT
            identifier: CACT
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: cactk8sprod1a
    - parallel:
        - stage:
            name: CTUS
            identifier: CTUS
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: ctusk8sprod1b
        - stage:
            name: ESUS 01
            identifier: ESUS01
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: esusk8sprod1a
        - stage:
            name: ESUS 02
            identifier: ESUS02
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: esus02k8sprod
        - stage:
            name: ESUS 03
            identifier: ESUS03
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: esus03k8sprod
        - stage:
            name: ESUS 04
            identifier: ESUS04
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: esus04k8sprod
        - stage:
            name: ESUS 05
            identifier: ESUS05
            description: ""
            type: Pipeline
            spec:
              org: RelativityOne_Compute
              pipeline: Deploy_Spark_Operator
              project: Spark
              inputs:
                identifier: Deploy_Spark_Operator
                stages:
                  - stage:
                      identifier: Deploy_Relativity_Components
                      type: Deployment
                      spec:
                        environment:
                          environmentRef: prod
                          infrastructureDefinitions:
                            - identifier: esus05k8sprod1a
    - stage:
        name: Send Deploy Event
        identifier: Send_Deploy_Event
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: Send Deploy Event
                  identifier: Send_Deploy_Event
                  template:
                    templateRef: Send_Deploy_Event
                    versionLabel: "1"
        tags: {}
