{{- if or .Values.rbac.create .Values.rbac.createRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-role
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - "*"
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark
  namespace: {{ default .Release.Namespace .Values.sparkJobNamespace }}
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
subjects:
{{- range $sparkJobNamespace := .Values.sparkJobNamespaces | default (list .Release.Namespace) }}
- kind: ServiceAccount
  name: {{ include "spark.serviceAccountName" $ }}
  namespace: {{ $sparkJobNamespace }}
{{- end }}
roleRef:
  kind: ClusterRole
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
